[package]
name = "aoc-2022-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pest = "2.5.1"
pest_derive = "2.5.1"
regex = "1.7.0"
